# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Privacy-Preserving Natural Language Processing
email: pthaine@cs.toronto.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD Candidate in Computer Science at the University of Toronto working on privacy and security applications for natural language processing. This blog will be going over new and exciting research at the intersection of cryptography, differential privacy, NLP, and ML.
baseurl: "" # the subpath of your site, e.g. /blog
url: "pathaine.github.io" # the base hostname & protocol for your site
twitter_username: CMcelephant
github_username:  pathaine

# Build settings
markdown: kramdown
